model_list:
  - model_name: "glm-4.7"  
    litellm_params:
      model: "openai/glm-4.7" # 使用通用的 openai/ 前缀
      api_base: "https://open.bigmodel.cn/api/paas/v4/"
      api_key: "os.environ/GLM_API_KEY"
  
  - model_name: "glm-4-flash"  
    litellm_params:
      model: "openai/glm-4-flash" # 使用通用的 openai/ 前缀
      api_base: "https://open.bigmodel.cn/api/paas/v4/"
      api_key: "os.environ/GLM_API_KEY"

  - model_name: "glm-4v-flash"  
    litellm_params:
      model: "openai/glm-4v-flash" 
      api_base: "https://open.bigmodel.cn/api/paas/v4/"
      api_key: "os.environ/GLM_API_KEY"

  - model_name: "embedding-3"
    litellm_params:
      model: "openai/embedding-3"
      api_base: "https://open.bigmodel.cn/api/paas/v4/"
      api_key: "os.environ/GLM_API_KEY"
  
  - model_name: "qwen3-max"  
    litellm_params:
      model: "openai/qwen3-max" 
      api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      api_key: "os.environ/QWEN_API_KEY"

  # --- 本地 Ollama ---
  - model_name: "qwen3-4b-local" 
    litellm_params:
      model: "ollama/qwen3:4b"
      api_base: "http://localhost:11434"
  
  - model_name: "qwen3-embedding-4b-local"
    litellm_params:
      model: "ollama/qwen3-embedding:4b"
      api_base: "http://localhost:11434"
      drop_params: True

server_settings:
  port: 4000
  host: "0.0.0.0"
